#!/usr/bin/env python3
"""Extract gettext markers from Spotty and trigger backends into po/spotty.pot.

Every user-facing string is marked in the source as gettext("…"); this
script collects them (with file:line references) into the catalogue that
po/<lang>.po files are based on. Run after adding or changing markers:

    scripts/extract_i18n.py
"""
import pathlib
import json
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCES = [ROOT / "src", ROOT / "trigger-backends" / "src"]
OUT = ROOT / "po" / "spotty.pot"
# gettext("literal") — literal may contain \" and \\ escapes (C-style, same
# escaping POT uses, so it passes through unchanged).
PATTERN = re.compile(r'gettext\(\s*"((?:[^"\\]|\\.)*)"\s*\)')


def main() -> None:
    entries: dict[str, list[str]] = {}
    for source in SOURCES:
        for path in sorted(source.rglob("*.rs")):
            for lineno, line in enumerate(path.read_text().splitlines(), 1):
                for m in PATTERN.finditer(line):
                    entries.setdefault(m.group(1), []).append(
                        f"{path.relative_to(ROOT)}:{lineno}"
                    )
    # Catalog descriptions come from the pinned trigger repository.
    catalog = ROOT / "trigger-backends" / "index.json"
    for entry in json.loads(catalog.read_text()):
        if entry.get("description"):
            msgid = json.dumps(entry["description"], ensure_ascii=False)[1:-1]
            entries.setdefault(msgid, []).append(str(catalog.relative_to(ROOT)))

    lines = [
        "# Spotty translation catalogue.",
        "# Generated by scripts/extract_i18n.py — do not edit by hand;",
        "# edit po/<lang>.po instead.",
        "msgid \"\"",
        "msgstr \"\"",
        '"Project-Id-Version: spotty\\n"',
        '"MIME-Version: 1.0\\n"',
        '"Content-Type: text/plain; charset=UTF-8\\n"',
        '"Content-Transfer-Encoding: 8bit\\n"',
        "",
    ]
    for msgid, locs in sorted(entries.items()):
        for loc in locs:
            lines.append(f"#: {loc}")
        lines.append(f'msgid "{msgid}"')
        lines.append('msgstr ""')
        lines.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"{OUT.relative_to(ROOT)}: {len(entries)} messages")


if __name__ == "__main__":
    main()
